# This is a configuration file example. You can edit it and add and remove torrents
# and magnet URIs. Read the following comments for more info.

# HTTP specific configuration.
http:
  port: 4444
  
  ip: "0.0.0.0"

  # Serve all routes content over http on IP:PORT/fs
  httpfs: true

# WebDAV specific configuration. Remove this to disable WebDAV.
webdav:
  port: 36911
  user: admin
  pass: admin

# Specific configuration for torrent backend.
torrent:
  # Size in MB for the cache. This is the maximum space used by distribyted to store
  # torrent data. Less used torrent data will be discarded if this value is reached.
  # global_cache_size: -1 #No limit
  global_cache_size: 2048

  # Folder where distribyted metadata will be stored.
  metadata_folder: ./distribyted-data/metadata

  # Disable IPv6.
  #disable_ipv6: true

  # Timeout in seconds when adding a magnet or a torrent.
  add_timeout: 60

  # Timeout in seconds when reading any torrent content. Usefult when reading 
  # archived content from .rar, .zip or .7z.
  read_timeout: 120

  # IP will change the default obtained IP from the default connection. Useful when
  # you are running inside a docker container. If you change this, you have to regenerate your ID file
  # located into the metadata folder.
  # ip: "1.2.3.4"

fuse:
  # Folder where fuse will mount torrent filesystem
  # For windows users: 
  #   - You can set here also a disk letter like X: or Z:.
  #   - The folder MUST NOT exists.
  path: ./distribyted-data/mount
  # Add this flag if you want to allow other users to access this fuse mountpoint.
  # You need to add user_allow_other flag to /etc/fuse.conf file.
  # allow_other: true 

log:
  path: ./distribyted-data/logs

  # MaxBackups is the maximum number of old log files to retain.  The default
	# is to retain all old log files (though MaxAge may still cause them to get
	# deleted.)
  max_backups: 2

  # MaxAge is the maximum number of days to retain old log files based on the
	# timestamp encoded in their filename.  Note that a day is defined as 24
	# hours and may not exactly correspond to calendar days due to daylight
	# savings, leap seconds, etc. The default is not to remove old log files
	# based on age.
  # max_age: 30

  # MaxSize is the maximum size in megabytes of the log file before it gets
	# rotated. It defaults to 100 megabytes.
  max_size: 50

  # debug: true

# List of folders where torrents will be mounted as a filesystem.
routes:
  - name: multimedia
    # Adding a folder will load all torrents on it:
    # torrent_folder: "/path/to/torrent/folder"
    torrents:
       # You can also add torrents from a specific path
       # - torrent_path: /path/to/torrent/file.torrent
       - magnet_uri: "magnet:?xt=urn:btih:c9e15763f722f23e98a29decdfae341b98d53056&dn=Cosmos+Laundromat&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fcosmos-laundromat.torrent"
       - magnet_uri: "magnet:?xt=urn:btih:dd8255ecdc7ca55fb0bbf81323d87062db1f6d1c&dn=Big+Buck+Bunny&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fbig-buck-bunny.torrent"
       - magnet_uri: "magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel.torrent"
       - magnet_uri: "magnet:?xt=urn:btih:209c8226b299b308beaf2b9cd3fb49212dbd13ec&dn=Tears+of+Steel&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Ftears-of-steel.torrent"
       - magnet_uri: "magnet:?xt=urn:btih:a88fda5954e89178c372716a6a78b8180ed4dad3&dn=The+WIRED+CD+-+Rip.+Sample.+Mash.+Share&tr=udp%3A%2F%2Fexplodie.org%3A6969&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.empire-js.us%3A1337&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fwired-cd.torrent"
# Example mountpoint containing some datasets, some of them compressed in zip format
  # - name: datasets
  #   torrents:
  #      - magnet_uri: "magnet:?xt=urn:btih:9dea07ba660a722ae1008c4c8afdd303b6f6e53b&tr=http%3A%2F%2Facademictorrents.com%2Fannounce.php&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969"
  #      - magnet_uri: "magnet:?xt=urn:btih:d8b3a315172c8d804528762f37fa67db14577cdb&tr=http%3A%2F%2Facademictorrents.com%2Fannounce.php&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969"
  #      - magnet_uri: "magnet:?xt=urn:btih:1e0a00b9c606cf87c03e676f75929463c7756fb5&tr=http%3A%2F%2Facademictorrents.com%2Fannounce.php&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce&tr=udp%3A%2F%2Ftracker.leechers-paradise.org%3A6969"

# List of folders where the content will be transformed to a magnet link. You can share any content sending that magnet link to others.
servers:
  - name: server
    path: ./distribyted-data/served-folders/server

    # Get trackers from web text file. The file will be loaded every time a magnet uri is generated,
    # so all trackers will be up to date.
    # tracker_url: "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_best.txt"

    # Trackers to be used to announce the served content. If tracker_url is set and it fails, 
    # this list will be used instead.
    trackers: 
      - "wss://tracker.btorrent.xyz"
      - "wss://tracker.openwebtorrent.com"
      - "http://p4p.arenabg.com:1337/announce"
      - "udp://tracker.opentrackr.org:1337/announce"
      - "udp://open.tracker.cl:1337/announce"
      - "http://openbittorrent.com:80/announce"
