---
name: build-32

# Trigger the workflow on push or pull request
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:

jobs:
  build_job:
    runs-on: ubuntu-20.04
    name: ubuntu-20.04 armv7
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0
      - uses: uraimo/run-on-arch-action@v2.1.1
        name: Test and Build
        id: runcmd
        with:
          arch: armv7
          distro: ubuntu20.04
          githubToken: ${{ github.token }}

          setup: |
            mkdir -p "${PWD}/artifacts"
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          install: |
            apt update
            apt install -y fuse libfuse-dev rpm pkg-config curl git make gcc g++
            apt upgrade -y
          run: |
            export PATH=$PATH:/usr/local/go/bin
            rm -rf /usr/local/go
            mkdir -p /usr/local/go 
            curl -s -L https://golang.org/dl/go1.17.linux-armv6l.tar.gz | tar -C /usr/local -xz
            go version

            make test
            make build
            cp bin/* /artifacts/
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          if-no-files-found: error
          name: build-armv7
          path: "${PWD}/artifacts/*"